<a href="https://colab.research.google.com/github/priyacoding/phonepe-pulse-data-visualization-and-exploration-/blob/main/GitClone_phonepe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/PhonePe/pulse

'git' is not recognized as an internal or external command,
operable program or batch file.

In [2]:
import os
import pandas as pd
import json

In [14]:
path_1 = "C:/Users/pmath/OneDrive/Desktop/pulse-master/pulse-master/data/aggregated/transaction/country/india/state/"
Agg_tran_state_list = os.listdir(path_1)

Agg_tra = {'State': [], 'Year': [], 'Quarter': [], 'Transaction_type': [], 'Transaction_count': [],
           'Transaction_amount': []}

for i in Agg_tran_state_list:
    p_i = path_1 + i + "/"
    Agg_yr = os.listdir(p_i)

    for j in Agg_yr:
        p_j = p_i + j + "/"
        Agg_yr_list = os.listdir(p_j)

        for k in Agg_yr_list:
            p_k = p_j + k
            Data = open(p_k, 'r')
            A = json.load(Data)

            for l in A['data']['transactionData']:
                Name = l['name']
                count = l['paymentInstruments'][0]['count']
                amount = l['paymentInstruments'][0]['amount']
                Agg_tra['State'].append(i)
                Agg_tra['Year'].append(j)
                Agg_tra['Quarter'].append(int(k.strip('.json')))
                Agg_tra['Transaction_type'].append(Name)
                Agg_tra['Transaction_count'].append(count)
                Agg_tra['Transaction_amount'].append(amount)

df_aggregated_transaction = pd.DataFrame(Agg_tra)

In [15]:
df_aggregated_transaction

,State,Year,Quarter,Transaction_type,Transaction_count,Transaction_amount
0,andaman-&-nicobar-islands,2018,1,Recharge & bill payments,4200,1.845307e+06
1,andaman-&-nicobar-islands,2018,1,Peer-to-peer payments,1871,1.213866e+07
2,andaman-&-nicobar-islands,2018,1,Merchant payments,298,4.525072e+05
3,andaman-&-nicobar-islands,2018,1,Financial Services,33,1.060142e+04
4,andaman-&-nicobar-islands,2018,1,Others,256,1.846899e+05
...,...,...,...,...,...,...
4129,west-bengal,2023,3,Merchant payments,296965002,2.004404e+11
4130,west-bengal,2023,3,Peer-to-peer payments,271150280,8.310501e+11
4131,west-bengal,2023,3,Recharge & bill payments,63055684,3.920985e+10
4132,west-bengal,2023,3,Financial Services,389751,4.249856e+08
4133,west-bengal,2023,3,Others,532474,4.232851e+08

In [16]:
df = df_aggregated_transaction.to_csv('Agg_tra.csv')

In [21]:
path_2 = "C:/Users/pmath/OneDrive/Desktop/pulse-master/pulse-master/data/aggregated/user/country/india/state/"
Agg_user_state_list = os.listdir(path_2)

Agg_user = {'State': [], 'Year': [], 'Quarter': [], 'Brands': [], 'User_Count': [], 'User_Percentage': []}

for i in Agg_user_state_list:
    p_i = path_2 + i + "/"
    Agg_yr = os.listdir(p_i)

    for j in Agg_yr:
        p_j = p_i + j + "/"
        Agg_yr_list = os.listdir(p_j)

        for k in Agg_yr_list:
            p_k = p_j + k
            Data = open(p_k, 'r')
            B = json.load(Data)

            try:
                for l in B["data"]["usersByDevice"]:
                    brand_name = l["brand"]
                    count_ = l["count"]
                    ALL_percentage = l["percentage"]
                    Agg_user["State"].append(i)
                    Agg_user["Year"].append(j)
                    Agg_user["Quarter"].append(int(k.strip('.json')))
                    Agg_user["Brands"].append(brand_name)
                    Agg_user["User_Count"].append(count_)
                    Agg_user["User_Percentage"].append(ALL_percentage * 100)
            except:
                pass

df_aggregated_user = pd.DataFrame(Agg_user)

In [22]:
df_aggregated_user

,State,Year,Quarter,Brands,User_Count,User_Percentage
0,andaman-&-nicobar-islands,2018,1,Xiaomi,1665,24.703264
1,andaman-&-nicobar-islands,2018,1,Samsung,1445,21.439169
2,andaman-&-nicobar-islands,2018,1,Vivo,982,14.569733
3,andaman-&-nicobar-islands,2018,1,Oppo,501,7.433234
4,andaman-&-nicobar-islands,2018,1,OnePlus,332,4.925816
...,...,...,...,...,...,...
6727,west-bengal,2022,1,Lenovo,330017,1.505567
6728,west-bengal,2022,1,Infinix,284678,1.298726
6729,west-bengal,2022,1,Asus,280347,1.278968
6730,west-bengal,2022,1,Apple,277752,1.267129
6731,west-bengal,2022,1,Others,2196334,10.019869

In [23]:
df1 = df_aggregated_user.to_csv('Agg_user.csv')

In [9]:
path_3 = "/content/pulse/data/map/transaction/hover/country/india/state/"
map_tra_state_list = os.listdir(path_3)

map_tra = {'State': [], 'Year': [], 'Quarter': [], 'District': [], 'Transaction_Count': [], 'Transaction_Amount': []}

for i in map_tra_state_list:
    p_i = path_3 + i + "/"
    Agg_yr = os.listdir(p_i)

    for j in Agg_yr:
        p_j = p_i + j + "/"
        Agg_yr_list = os.listdir(p_j)

        for k in Agg_yr_list:
            p_k = p_j + k
            Data = open(p_k, 'r')
            C = json.load(Data)

            for l in C["data"]["hoverDataList"]:
                District = l["name"]
                count = l["metric"][0]["count"]
                amount = l["metric"][0]["amount"]
                map_tra['State'].append(i)
                map_tra['Year'].append(j)
                map_tra['Quarter'].append(int(k.strip('.json')))
                map_tra["District"].append(District)
                map_tra["Transaction_Count"].append(count)
                map_tra["Transaction_Amount"].append(amount)

df_map_transaction = pd.DataFrame(map_tra)

In [10]:
df_map_transaction

,State,Year,Quarter,District,Transaction_Count,Transaction_Amount
0,meghalaya,2020,3,north garo hills district,17943,2.361825e+07
1,meghalaya,2020,3,south west khasi hills district,5942,8.330565e+06
2,meghalaya,2020,3,west garo hills district,117550,2.495759e+08
3,meghalaya,2020,3,south garo hills district,17171,2.336865e+07
4,meghalaya,2020,3,east jaintia hills district,52534,9.966988e+07
...,...,...,...,...,...,...
16827,west-bengal,2019,1,nadia district,1878230,1.674723e+09
16828,west-bengal,2019,1,birbhum district,5081745,6.063627e+09
16829,west-bengal,2019,1,purba medinipur district,2175167,2.426138e+09
16830,west-bengal,2019,1,maldah district,1559418,1.770445e+09
16831,west-bengal,2019,1,darjiling district,560839,9.333577e+08

In [11]:
df3 = df_map_transaction.to_csv('map_tra.csv')

In [12]:
path_4 = "/content/pulse/data/map/user/hover/country/india/state/"
map_user_state_list = os.listdir(path_4)

map_user = {"State": [], "Year": [], "Quarter": [], "District": [], "Registered_User": []}

for i in map_user_state_list:
    p_i = path_4 + i + "/"
    Agg_yr = os.listdir(p_i)

    for j in Agg_yr:
        p_j = p_i + j + "/"
        Agg_yr_list = os.listdir(p_j)

        for k in Agg_yr_list:
            p_k = p_j + k
            Data = open(p_k, 'r')
            D = json.load(Data)

            for l in D["data"]["hoverData"].items():
                district = l[0]
                registereduser = l[1]["registeredUsers"]
                map_user['State'].append(i)
                map_user['Year'].append(j)
                map_user['Quarter'].append(int(k.strip('.json')))
                map_user["District"].append(district)
                map_user["Registered_User"].append(registereduser)

df_map_user = pd.DataFrame(map_user)

In [13]:
df_map_user

,State,Year,Quarter,District,Registered_User
0,meghalaya,2020,3,north garo hills district,5242
1,meghalaya,2020,3,south west khasi hills district,1169
2,meghalaya,2020,3,west garo hills district,34201
3,meghalaya,2020,3,south garo hills district,4370
4,meghalaya,2020,3,east jaintia hills district,11084
...,...,...,...,...,...
16831,west-bengal,2019,1,nadia district,385179
16832,west-bengal,2019,1,birbhum district,265201
16833,west-bengal,2019,1,purba medinipur district,389583
16834,west-bengal,2019,1,maldah district,266012
16835,west-bengal,2019,1,darjiling district,145181

In [14]:
df = df_map_user.to_csv('map_user.csv')

In [15]:
path_5 = "/content/pulse/data/top/transaction/country/india/state/"
top_tra_state_list = os.listdir(path_5)

top_tra = {'State': [], 'Year': [], 'Quarter': [], 'District_Pincode': [], 'Transaction_count': [],
           'Transaction_amount': []}

for i in top_tra_state_list:
    p_i = path_5 + i + "/"
    Agg_yr = os.listdir(p_i)

    for j in Agg_yr:
        p_j = p_i + j + "/"
        Agg_yr_list = os.listdir(p_j)

        for k in Agg_yr_list:
            p_k = p_j + k
            Data = open(p_k, 'r')
            E = json.load(Data)

            for l in E['data']['pincodes']:
                Name = l['entityName']
                count = l['metric']['count']
                amount = l['metric']['amount']
                top_tra['State'].append(i)
                top_tra['Year'].append(j)
                top_tra['Quarter'].append(int(k.strip('.json')))
                top_tra['District_Pincode'].append(Name)
                top_tra['Transaction_count'].append(count)
                top_tra['Transaction_amount'].append(amount)

df_top_transaction = pd.DataFrame(top_tra)

In [16]:
df_top_transaction

,State,Year,Quarter,District_Pincode,Transaction_count,Transaction_amount
0,meghalaya,2020,3,793001,64872,1.847436e+08
1,meghalaya,2020,3,793210,30783,5.754587e+07
2,meghalaya,2020,3,793101,27591,6.621543e+07
3,meghalaya,2020,3,793002,25567,6.080274e+07
4,meghalaya,2020,3,794001,25373,5.066460e+07
...,...,...,...,...,...,...
8205,west-bengal,2019,1,713145,335528,2.917228e+08
8206,west-bengal,2019,1,700091,333939,3.298645e+08
8207,west-bengal,2019,1,713201,271824,2.583108e+08
8208,west-bengal,2019,1,734006,238641,3.182200e+08
8209,west-bengal,2019,1,721101,238165,2.237861e+08

In [17]:
df = df_top_transaction.to_csv('top_tra.csv')

In [18]:
path_6 = "/content/pulse/data/top/user/country/india/state/"
top_user_state_list = os.listdir(path_6)

top_user = {'State': [], 'Year': [], 'Quarter': [], 'District_Pincode': [], 'Registered_User': []}

for i in top_user_state_list:
    p_i = path_6 + i + "/"
    Agg_yr = os.listdir(p_i)

    for j in Agg_yr:
        p_j = p_i + j + "/"
        Agg_yr_list = os.listdir(p_j)

        for k in Agg_yr_list:
            p_k = p_j + k
            Data = open(p_k, 'r')
            F = json.load(Data)

            for l in F['data']['pincodes']:
                Name = l['name']
                registeredUser = l['registeredUsers']
                top_user['State'].append(i)
                top_user['Year'].append(j)
                top_user['Quarter'].append(int(k.strip('.json')))
                top_user['District_Pincode'].append(Name)
                top_user['Registered_User'].append(registeredUser)

df_top_user = pd.DataFrame(top_user)

In [19]:
df_top_user

            State  Year  Quarter District_Pincode  Registered_User
0       meghalaya  2020        3           793001            16464
1       meghalaya  2020        3           793002             9658
2       meghalaya  2020        3           794001             8252
3       meghalaya  2020        3           794105             7516
4       meghalaya  2020        3           793011             7165
...           ...   ...      ...              ...              ...
8206  west-bengal  2019        1           721101            36261
8207  west-bengal  2019        1           700039            33907
8208  west-bengal  2019        1           700015            33113
8209  west-bengal  2019        1           700019            32710
8210  west-bengal  2019        1           700001            32530

[8211 rows x 5 columns]

In [20]:
df = df_top_user.to_csv('top_user.csv')